### ISSUE TITLE
Error processing referral: timeout 120.0 exceeded

### ISSUE THREAD

**Issue by itschandra02** [im-hanzou/nodepay-autoref#10]
![Screenshot_2024-11-14-21-43-06-291_com termux](https://github.com/user-attachments/assets/386f0e80-f93c-4124-9a7a-25d6c296c721)

Bang ini kenapa erorr bang status nya : Error processing referral: timeout 120.0 exceeded

**Comment by im-hanzou** [comment]
itu proxy atau networkmu down ya, coba ganti proxy atau ganti koneksi internet

key captcha di sensor ya atau ssnya dihapus, takut dipake orang
