### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by worktoichoi** [im-hanzou/nodepay-autoref#11]
![case](https://github.com/user-attachments/assets/9c364c20-6aad-4e9d-97f1-79fbdc5b7fa5)
Can I ask why it reports an error? I have added the proxy as well as the captcha solving api! In the accounts.txt file, do I need to create it and add the mail account? Please help me, thank you.

**Comment by im-hanzou** [comment]
your referal code is wrong bro, just input the code not the referral link

for example:
Insert your referral code, example: https://app.nodepay.ai/register?ref=XXXXXXXXXX this is your code: XXXXXXXXXX

**Comment by worktoichoi** [comment]
Thanks for understanding! Can you tell me where Gmail or Hotmail accounts are created?

**Comment by im-hanzou** [comment]
> Thanks for understanding! Can you tell me where Gmail or Hotmail accounts are created?

no mails account created. just nodepay accounts created. check accounts.txt
