### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Godfatherangle** [im-hanzou/nodepay-autoref#12]
It's only show attempts not working not able to successfully refer

**Comment by im-hanzou** [comment]
did you enter your referral code correctly or proxies format (http proxies only). i still use this script and my referral still increased

**Comment by Godfatherangle** [comment]
i use webshare free proxy username base and which api use for captcha is free api ?

**Comment by im-hanzou** [comment]
captcha api is paid. make sure you charge your credit first

**Comment by Godfatherangle** [comment]
oh thats points can u suggest which is use u

**Comment by im-hanzou** [comment]
i use 2captcha and anticaptcha, check readme
