### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by benjzone** [im-hanzou/nodepay-autoref#14]
![requirments](https://github.com/user-attachments/assets/a5a8f730-93b7-4734-9af5-f8e6255a8350)

Bang kalo kayak gini kenapa?
ga nisa install requirements.txt

**Comment by benjzone** [comment]
udah bisa bang,, salah masuk directorynya.. hehe

**Comment by im-hanzou** [comment]
njir wkwk
