### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by benjzone** [im-hanzou/nodepay-autoref#15]
![error](https://github.com/user-attachments/assets/71191b6a-6b87-4f19-b672-2a755a76aef2)
bang kalo kaya gini knp? plis help

**Comment by im-hanzou** [comment]
udah ngikutin stepnya kah?

**Comment by benjzone** [comment]
udah om

**Comment by im-hanzou** [comment]
install requirements.txt dulu, itu belum install

pip install -r requirements.txt

**Comment by benjzone** [comment]
![1234](https://github.com/user-attachments/assets/95efa825-85bd-4753-ad5e-5b104d6610b5)

udah om tetep sama..

**Comment by im-hanzou** [comment]
pip install faker

coba

**Comment by benjzone** [comment]
![11](https://github.com/user-attachments/assets/ce963f57-e583-486a-9988-435ce0be3d8d)
udah om hasil masih sama.

**Comment by im-hanzou** [comment]
python -m pip install -r requirements.txt
python -m pip install faker

itu pythonmu dobel mungkin bang di devicemu
