### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by yazidnabm** [im-hanzou/nodepay-autoref#16]
![nodepay](https://github.com/user-attachments/assets/031fd0c7-891b-46e9-9669-cef544aeee3f)

ini knp ya bang? ane pke proxy gratisan dri webshare, api captcha jg ada saldonya, ref nya jg udh sesuai, apa emg lagi eror kah?

**Comment by im-hanzou** [comment]
proxymu error ya itu, referral kodemu juga salah

**Comment by yazidnabm** [comment]
proxy gratisan dri webshare bisa kan yaa? apa harus berbayar? reff codenya juga udah sesuai format bang itu

**Comment by im-hanzou** [comment]
bisa, tapi recomended paid ya
dicoba dulu

**Comment by yazidnabm** [comment]
oke bang thanks infonyaa ane cba" lagii
