### ISSUE TITLE
reff pending

### ISSUE THREAD

**Issue by zsxsz** [im-hanzou/nodepay-autoref#2]
reff pending

**Comment by anyepsss** [comment]
New zbless Node.. will get repo?

**Comment by im-hanzou** [comment]
next version will be updated, still processing

**Comment by zsxsz** [comment]
> next version will be updated, still processing

When you have successfully created an account, the account must activate the Nodepay extension so that refs can enter, I hope you can create it, thank you

**Comment by im-hanzou** [comment]
Script updated, Please git pull or re-download the script!

**Comment by zsxsz** [comment]
terimakasih bang hanzou
, yg lain pada jualan tpi ini free

**Comment by anyepsss** [comment]
> Script updated, Please git pull or re-download the script!

Yg ini aja kan yg perlu di update? Yg lain belum
