### ISSUE TITLE
please make bot auto confirm wallet to email

### ISSUE THREAD

**Issue by Maillev** [im-hanzou/nodepay-autoref#22]
hello bro, can you make a script auto confirm wallet address to email on nodepay? please respond to my question ASAP. thanks.

**Comment by im-hanzou** [comment]
yes, but i can't made it for now

**Comment by Maillev** [comment]
when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!

**Comment by im-hanzou** [comment]
> when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!

unauthorized is error from nodepay server

**Comment by Maillev** [comment]
If it is solved by using a script, will the result still be an error or what, bro?

> > when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!
> 
> unauthorized is error from nodepay server

If it is solved by using a script, will the result still be an error or what, bro?

**Comment by Maillev** [comment]
> > when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!
> 
> unauthorized is error from nodepay server

If it is solved by using a script, will the result still be an error or what, bro?

**Comment by im-hanzou** [comment]
> > > when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!
> > 
> > 
> > unauthorized is error from nodepay server
> 
> If it is solved by using a script, will the result still be an error or what, bro?

yes still error, cause error from server

**Comment by Maillev** [comment]
> > > > when do you think you have time to make the script bro? I really need it. because I can't confirm the wallet to email manually. always **'unauthorize error'**?!?!
> > > 
> > > 
> > > unauthorized is error from nodepay server
> > 
> > 
> > If it is solved by using a script, will the result still be an error or what, bro?
> 
> yes still error, cause error from server

what I wonder since the beginning since I did it, there have been errors for some people. but there are also those who are normal and can immediately confirm the wallet to the email. I don't know I'm also confused why it's like that even though I've followed the tutorial on their discord and twitter. but still the problem is not resolved. I'm very tired of not finding the right solution.😌

**Comment by im-hanzou** [comment]
yeah, currently nodepay is doing a major update to anticipate cheaters. maybe thats the impact.

**Comment by Maillev** [comment]
> yeah, currently nodepay is doing a major update to anticipate cheaters. maybe thats the impact.

yes that's right bro. if for example they update the nodepay extension to a new version, can it solve this problem bro?🤔

**Comment by im-hanzou** [comment]
yes can be, or you can open ticket at their discord

**Comment by Maillev** [comment]
thanks for sharing bro. my problem has been resolved and has successfully confirmed the wallet to email. maybe another time we can discuss again. 🙏🙏
