### ISSUE TITLE
Get Error

### ISSUE THREAD

**Issue by celiaraish** [im-hanzou/nodepay-autoref#24]
![image](https://github.com/user-attachments/assets/628c03c7-8168-49d1-83de-1d2e8dd14952)

![image](https://github.com/user-attachments/assets/10fe3180-e0ec-4bf2-9c22-15467158a5eb)

can help pls? my credit to low or script need update?

**Comment by duongdinhmanh123** [comment]
Me too

**Comment by im-hanzou** [comment]
Please use latest Python version
