### ISSUE TITLE
Pending 

### ISSUE THREAD

**Issue by DezXBT** [im-hanzou/nodepay-autoref#3]
Tambahkan fitur agar tidak pending bang

**Comment by im-hanzou** [comment]
next version ya, lagi diproses

**Comment by himaherawan** [comment]
Woke

**Comment by zsxsz** [comment]
> next version ya, lagi diproses

Apabila anda sudah berhasil membuat akun, maka akun tersebut harus mengaktifkan extension Nodepay agar referensi bisa masuk, semoga anda bisa membuatnya, terima kasih

**Comment by im-hanzou** [comment]
Script updated, Please git pull or re-download the script!

**Comment by DezXBT** [comment]
> Script updated, Please git pull or re-download the script!

Gg bang
