### ISSUE TITLE
Registration failed

### ISSUE THREAD

**Issue by yudhistirank** [im-hanzou/nodepay-autoref#4]
bang kenapa invalid yak padahal udah bener reff ku

![Screenshot 2024-11-14 080541](https://github.com/user-attachments/assets/7793f155-1a68-4083-910e-1a347f36df38)

**Comment by im-hanzou** [comment]
referral code mu invalid itu bro, akun langsung print dari response server apinya buat ngecek dimana kesalahannya.

**Comment by yudhistirank** [comment]
Response Status Code: 200
Response JSON: {'success': False, 'code': 5, 'msg': 'Invalid referral code', 'data': None}
[17:27:55] ✗ Registration failed: Invalid referral code

padahal aku copy reff dari web nya lgsg loh
ada reff nanggur ga bg, biar ku coba

**Comment by im-hanzou** [comment]
coba: KZoiupoQxqjaZ6s

**Comment by yudhistirank** [comment]
Tuh bang sama aja ;V

![Screenshot 2024-11-14 083844](https://github.com/user-attachments/assets/725424c0-69df-4f05-a0ef-6ec8c87896ec)
![Screenshot 2024-11-14 083912](https://github.com/user-attachments/assets/ba9ee8f0-60d7-4af2-a2a2-a75303f5d3f1)

**Comment by im-hanzou** [comment]
bang cuma kode ref nya, jangan full link. contoh:

Enter referral code: KZoiupoQxqjaZ6s

**Comment by yudhistirank** [comment]
anjim lah ku kira pake link nya, don bang thanks :D

**Comment by im-hanzou** [comment]
woke sama-sama
