### ISSUE TITLE
Pending reff

### ISSUE THREAD

**Issue by Poxezy** [im-hanzou/nodepay-autoref#6]
Apa sudah auto Jalanin refnya skrg mas || tidak pending ?

**Comment by im-hanzou** [comment]
iya betul, sudah tidak pending

**Comment by Poxezy** [comment]
Setelah mendapatkan account code apakah harus di jalankan 1 per 1?

**Comment by im-hanzou** [comment]
tidak bang, akun langsung aktif, 
tapi kalau mau dapet pasif earn dari referral, boleh di bot lagi make ini: https://github.com/im-hanzou/nodepay-automate tinggal paste token saja
