### ISSUE TITLE
nodepay-automate issue

### ISSUE THREAD

**Issue by professordevil25** [im-hanzou/nodepay-autoref#7]
i use bypass option but proxy not called api..please apply old session method. code line 32 in bypass python file.your old method work but update method not work

**Comment by im-hanzou** [comment]
okay, but why you open issue in this repo bruh 💀

**Comment by professordevil25** [comment]
> okay, but why you open issue in this repo bruh 💀

Error during API call: 403 Client Error: Forbidden for url: https://api.nodepay.org/api/auth/session  
Error in render_profile_info for proxy http://2b43627548c095802__cr.us:d16dcd185ba35@148.251.5.30:823: Failed API call to https://api.nodepay.org/api/auth/session

i face  this error brother

**Comment by im-hanzou** [comment]
are you using run.py?

**Comment by professordevil25** [comment]
> are you using run.py?

no.python run-bypass.py

**Comment by professordevil25** [comment]
![image](https://github.com/user-attachments/assets/d157aed3-6e77-4c04-ae13-83dfc02a6367)
![image](https://github.com/user-attachments/assets/fcd19df1-04c6-4e63-acba-6e15898e43a6)


> are you using run.py?

**Comment by im-hanzou** [comment]
so, you mean changing the auth method from using  domain host to IP host, right?

**Comment by professordevil25** [comment]
> so, you mean changing the auth method from using domain host to IP host, right?

Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.

**Comment by professordevil25** [comment]
> so, you mean changing the auth method from using domain host to IP host, right?

yes.maybe this method working

**Comment by im-hanzou** [comment]
> > so, you mean changing the auth method from using domain host to IP host, right?
> 
> Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.

currently nodepay ip host for ping method is down. so you can run original version (run.py) only, will be updated if i find another hosts

**Comment by professordevil25** [comment]
> > > so, you mean changing the auth method from using domain host to IP host, right?
> > 
> > 
> > Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.
> 
> currently nodepay ip host for ping method is down. so you can run original version (run.py) only, will be updated if i find another hosts

okay brother

**Comment by professordevil25** [comment]
> > > so, you mean changing the auth method from using domain host to IP host, right?
> > 
> > 
> > Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.
> 
> currently nodepay ip host for ping method is down. so you can run original version (run.py) only, will be updated if i find another hosts

run.py not working for me.its problem brother.i waiting for your update.

**Comment by im-hanzou** [comment]
okay bro

**Comment by im-hanzou** [comment]
> > > > so, you mean changing the auth method from using domain host to IP host, right?
> > > 
> > > 
> > > Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.
> > 
> > 
> > currently nodepay ip host for ping method is down. so you can run original version (run.py) only, will be updated if i find another hosts
> 
> run.py not working for me.its problem brother.i waiting for your update.

updated, use new (run-bypass.py) script, but this host not stable. some time down sometime up, give it a try

**Comment by professordevil25** [comment]
> > > > > so, you mean changing the auth method from using domain host to IP host, right?
> > > > 
> > > > 
> > > > Bro you solved this problem. Your old method works but this method does not work. I don't have proper knowledge.i sent you 2 ss.you see this please.
> > > 
> > > 
> > > currently nodepay ip host for ping method is down. so you can run original version (run.py) only, will be updated if i find another hosts
> > 
> > 
> > run.py not working for me.its problem brother.i waiting for your update.
> 
> updated, use new (run-bypass.py) script, but this host not stable. some time down sometime up, give it a try

not working bro.maybe you change again.please sent me domain host link. you tell me where i can inter.
