### ISSUE TITLE
reff issue

### ISSUE THREAD

**Issue by Poxezy** [im-hanzou/nodepay-autoref#9]
![image](https://github.com/user-attachments/assets/51e5c621-e478-4b06-80c4-c89511906416)
bang ini ko gua error ref ya pdhal dh bner

**Comment by im-hanzou** [comment]
key 2captcha salah ya, pastiin di dashboard pilih role developer dulu

**Comment by Poxezy** [comment]
buat proxynya di depannya harus nulisin https:// ya mas?

**Comment by im-hanzou** [comment]
iya tambahin http:// , sesuai format
